### ISSUE TITLE
Empty Rooms Stuck in List

### ISSUE THREAD

**Issue by dinodude7777** [tulir/gomuks#169] opened 2020-05-18 01:49 UTC
Just installed via gomuks-git on Manjaro. Empty rooms, which I think used to be DMs I was in and previously left, are stuck in my People list. Tried /clearcache and going to the rooms and using /leave, but those did nothing to help the issue.
![image](https://user-images.githubusercontent.com/44576802/82166990-49d6a780-9888-11ea-9bcf-6814a7aafc8a.png)

**Comment by tulir** [comment] 2020-05-18 10:17
Duplicate of #162

**Closed by tulir** 2020-05-18 10:17 UTC
Labels: duplicate
