### ISSUE TITLE
backspace erases entire words

### ISSUE THREAD

**Issue by prahou** [tulir/gomuks#457] opened 2024-04-28 09:44 UTC
On FreeBSD 14.0

When composing a message, if backspace is pressed, the entire last word is erased (up until the closest whitespace)
If Ctrl+Backspace is pressed, only one character is erased, this should be the default behavior?

**Comment by tulir** [comment] 2024-04-28 12:29
Duplicate of #322

**Closed by tulir** 2024-04-28 12:29 UTC
