### ISSUE TITLE
Text whose sum of character size's is greater than 117 bits is splitted when pasting it into the message prompt.

### ISSUE THREAD

**Issue by ghost** [tulir/gomuks#165] opened 2020-05-12 11:52 UTC
# The problem

I am used to edit text in `vim`, this is the reason why I noticed this problem: Pasting the following message

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

into the message prompt would result in sending a message with the following content

```

~[200~aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

while leaving the following

```
[201~
```

in the message prompt.

# Additional context

The reason why I state that messages with more than 117 bits are splitted is because of a set of experiments that I carried out which are explained below. The fact that messages with more than 117 bits are splitted is just an hypothesis which was obtained because of the experiments, it hasn't been fully proved.

The experiments were carried out by performing the following steps

1. Content was inserted in the `1.txt` file.
2. Number of bits present in the file was obtained with `du -b 1.txt`.
3. Content of `1.txt` was inserted into the clipboard executing the command presented below.

```
$ xclip -sel c < 1.txt
```

4. Content of the clipboard was inserted into the `gomuks` message prompt by pressing `<Shift+Ctrl+V>` while using the `st` terminal emulator.

The problem occurred with the following messages

(117 bits)

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

(117 bits)

```
わわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわaa
```

The problem didn't occur with the following messages

(116 bits)

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

(116 bits)

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

(116 bits)

```
Putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodema
```

(116 bits)

```
わわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわわa
```

# The solution

Wouldn't it be better if the message prompt didn't split messages? Thus, users would be able to use their favorite text editor to edit a message for, then, pasting it into the `gomuks` message prompt.

**Comment by tulir** [comment] 2020-05-12 12:05
Weird bug, this is probably related to how bracketed pasting works.

The [upstream tcell](https://github.com/gdamore/tcell/) package doesn't support bracketed pasting, which means pastes are just interpreted as key events, which quickly fills up buffers and drops characters. Due to that loss of data, [my fork of tcell](https://github.com/tulir/tcell) is based on [another fork of tcell](https://github.com/zyedidia/tcell) with bracketed pasting support. I can reproduce similar behavior in [micro](https://github.com/zyedidia/micro), so it's likely that the bug is in tcell.

Anyway, the easiest solution is to use <kbd>Ctrl</kbd>+<kbd>V</kbd> (no <kbd>Shift</kbd>) to bypass the terminal altogether.

**Comment by rmo20** [comment] 2020-05-12 12:26
Yes, you're right, pressing `Ctrl` + `V` solves the problem. This works in both `st 0.8.2` and `urxvt 9.22`.

Thanks for the rapid answer.

**Comment by tulir** [comment] 2022-04-15 10:30
This should be fixed with the tcell v2 update (upstream added bracketed paste support which seems to work correctly)

**Closed by tulir** 2022-04-15 10:30 UTC
Labels: bug
