### ISSUE TITLE
Cannot verify gomuks session

### ISSUE THREAD

**Issue by julianuu** [tulir/gomuks#271] opened 2021-03-11 13:19 UTC
When I try to verify from element, it says in element

You cancelled verification on your other session. Start verification again from the notification.

I tried clearing the cache, and removing all the files from .config, .local and .share, didn't fix it

**Comment by tulir** [comment] 2021-03-11 13:23
Duplicate of #205

**Closed by tulir** 2021-03-11 13:23 UTC

**Comment by julianuu** [comment] 2021-03-11 13:26
sorry I hadn't realized
