### ISSUE TITLE
Invalid password

### ISSUE THREAD

**Issue by gekoke** [tulir/gomuks#358] opened 2022-04-01 18:02 UTC
Perhaps this is user error, but I seem to not be able to authenticate when pasting a very long password.
Terminal emulator: Alacritty
Server: matrix.org
Password:
```8ksmP#SZA19V204w1a0JExfE4RigpcoXDHkH6UMv%7Kc%WZwVaXDarso&!2GbKu7A2kmx0HAqQ1*LrlDN%5Z5GluELHLXH7tsSDYapF8WwX$hvMTQ&bNQx%G0jfo*j8l```

![image](https://user-images.githubusercontent.com/63151928/161317332-b148852c-ecb7-42a4-99b0-f33e664f140a.png)

I was able to authenticate following precisely the same steps after changing my password to be 64 character [a-Z][0-9], so I believe this is somehow a limitation of the input field/pasting.

**Comment by tulir** [comment] 2022-04-15 10:30
Duplicate of #165

**Closed by tulir** 2022-04-15 10:30 UTC
