### ISSUE TITLE
Macos dont start

### ISSUE THREAD

**Issue by Madaspe** [tulir/gomuks#352] opened 2022-03-15 19:57 UTC
```
 __________
< Oh noes! >
 ‾‾‾\‾‾‾‾‾‾
     \   ^__^
      \  (XX)\_______
         (__)\       )\/\
          U  ||----W |
             ||     ||

A fatal error has occurred.

The stack trace has been saved to /var/folders/pp/_8qj4m0n1lsgbvr3vqz63fvh0000gn/T/gomuks/panic-2022-03-16--00-54-41.txt

You can file an issue at https://github.com/tulir/gomuks/issues.
Please provide the contents of that file when filing an issue.
```

/var/folders/pp/_8qj4m0n1lsgbvr3vqz63fvh0000gn/T/gomuks/panic-2022-03-16--00-54-41.txt
```
exit status 1
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x88
maunium.net/go/gomuks/debug.PrettyPanic({0x101bf4060, 0x140004f2060})
        maunium.net/go/gomuks/debug/debug.go:133 +0x1a8
maunium.net/go/gomuks/debug.Recover()
        maunium.net/go/gomuks/debug/debug.go:107 +0x80
panic({0x101bf4060, 0x140004f2060})
        runtime/panic.go:1038 +0x21c
main.(*Gomuks).Start(0x1400011e4e0)
        maunium.net/go/gomuks/gomuks.go:116 +0x130
main.main()
        maunium.net/go/gomuks/main.go:89 +0x6e4
```

Macbook 2020 M1

Install with `brew install aaronraimist/tap/gomuks`

**Comment by aaronraimist** [comment] 2022-03-16 12:57
Works fine for me on macOS 12.3 on an Apple Silicon Mac. Are you using tmux? https://github.com/tulir/gomuks/issues/250

**Comment by Madaspe** [comment] 2022-03-16 17:32
Yes, I use tmux

**Comment by aaronraimist** [comment] 2022-03-16 17:57
Then this is likely a duplicate of https://github.com/tulir/gomuks/issues/250

**Closed** 2022-03-26 17:12 UTC
