### ISSUE TITLE
Mouse hover over emoji reaction should indicate who sent the reaction

### ISSUE THREAD

**Issue by ajkessel** [tulir/gomuks#539] opened 2024-12-06 14:58 UTC
Mouse-hover over a reaction now just shows you a tool-tip with the reaction. In order to know who sent the reaction, the tool-tip should provide the username of the person who sent the reaction.

**Comment by tulir** [comment] 2024-12-06 14:59
This is basically a duplicate of #484

**Closed by tulir** 2024-12-06 14:59 UTC
