### ISSUE TITLE
Annoying "More/Less" buttons that disrupt the keyboard workflow

### ISSUE THREAD

**Issue by fbushstone** [tulir/gomuks#248] opened 2020-11-25 16:05 UTC
There are some annoying "More/Less" buttons that I have to click on with my mouse- these should be either off by default, removed completely, or have a setting for them to be disabled.
![2020-11-25-105451_1920x1200_scrot](https://user-images.githubusercontent.com/66080865/100252027-6aee1400-2f0d-11eb-9e44-40c063adaba5.png)

**Comment by jcromero** [comment] 2020-12-02 09:58
Why do you have to click on those buttons?

**Comment by InfiniteWorldSoftware** [comment] 2020-12-02 22:30
> Why do you have to click on those buttons?

Some rooms are hidden and there is no keyboard shortcut expand the room list.
I've tried making a few modifications to the code itself but I haven't had the drive to do anything serious towards disabling them.

**Comment by jcromero** [comment] 2020-12-02 22:41
I suppose you know that you can open those rooms with Crtl+k and entering some letters in their name

**Comment by InfiniteWorldSoftware** [comment] 2020-12-02 22:47
Yeah. Although, that's not a way to disable the More/Less buttons- it's room expansion with extra steps.

**Comment by jcromero** [comment] 2020-12-02 22:49
But my question is, do you really need to expand the room list?

**Comment by InfiniteWorldSoftware** [comment] 2020-12-02 22:50
Yes. That's why I created the issue.

**Comment by jcromero** [comment] 2020-12-02 22:56
Updated question 😉

**Comment by InfiniteWorldSoftware** [comment] 2020-12-02 22:57
Oh, thanks. Whenever I start gomuks. But it is still annoying having to expand the roomlist every time.

**Comment by jcromero** [comment] 2020-12-03 08:17
The issue is that if you have a lot of rooms, classified by tags, I prefer, by default, to be able to see the first 10 rooms in each tag, that miss several tags in the global view if one of them has a lot of rooms. That's why I asked you why do you need to have those tags expanded.

**Comment by Lertsenem** [comment] 2021-01-26 14:31
I have this issue too. A good solution would be to be able to use those More/Less buttons from the keyboard (highlight them and use enter or space for example?).

**Comment by vtrgnc** [comment] 2024-01-25 10:43
I know it has been some time since this was posted; however, I do have the same issue. My suggestion is that there could be a `/toggle` option to toggle the more/less buttons, and also that when navigating with the Ctrl+↓ or Ctrl+↑, the room list autoexpanded to see all the rooms, also toggleable maybe. I could help implement this feature, but I want to see if I have support and the PR would be merged.

**Closed** 2024-11-10 19:41 UTC
